#!/bin/bash

# Script per configurare Mosquitto con supporto WebSocket
# Da eseguire sul Raspberry Pi se check_mosquitto_esterno.sh rileva problemi

echo ""
echo "============================================================"
echo "  🔧 FIX CONFIGURAZIONE MOSQUITTO WEBSOCKET"
echo "============================================================"
echo ""

# Colori
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Trova directory progetto
if [ -d "escape-room-3d" ]; then
    PROJECT_DIR="escape-room-3d"
elif [ -d "../escape-room-3d" ]; then
    PROJECT_DIR="../escape-room-3d"
else
    echo -e "${RED}❌ Directory escape-room-3d non trovata!${NC}"
    echo "Esegui questo script dalla directory contenente escape-room-3d"
    exit 1
fi

echo "📁 Directory progetto: $PROJECT_DIR"
echo ""

# Verifica se Mosquitto è in esecuzione
if ! docker ps | grep -q mosquitto; then
    echo -e "${YELLOW}⚠️  Mosquitto non in esecuzione${NC}"
    echo "Avvio Mosquitto..."
    cd "$PROJECT_DIR"
    docker-compose up -d mosquitto
    sleep 3
fi

# Trova container ID
MOSQUITTO_ID=$(docker ps --filter "name=mosquitto" --format "{{.ID}}")

if [ -z "$MOSQUITTO_ID" ]; then
    echo -e "${RED}❌ Impossibile trovare container Mosquitto!${NC}"
    exit 1
fi

echo "🐳 Container Mosquitto: $MOSQUITTO_ID"
echo ""

# ==================================================
# Backup configurazione esistente
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Backup Configurazione"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

BACKUP_FILE="$PROJECT_DIR/mosquitto/config/mosquitto.conf.backup.$(date +%Y%m%d_%H%M%S)"
docker exec $MOSQUITTO_ID cat /mosquitto/config/mosquitto.conf > "$BACKUP_FILE" 2>/dev/null

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Backup salvato: $BACKUP_FILE${NC}"
else
    echo -e "${YELLOW}⚠️  Backup non riuscito (file potrebbe non esistere)${NC}"
fi

echo ""

# ==================================================
# Crea nuova configurazione
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Crea Nuova Configurazione"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Configurazione ottimale per ESP32 + Frontend WebSocket
cat > "$PROJECT_DIR/mosquitto/config/mosquitto.conf" << 'EOF'
# Mosquitto Configuration for ESP32 + Frontend WebSocket
# Auto-generated by fix_mosquitto_config.sh

# Listener MQTT (porta 1883) - per ESP32
listener 1883
protocol mqtt
allow_anonymous true

# Listener WebSocket (porta 9001) - per Frontend
listener 9001
protocol websockets
allow_anonymous true

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Persistence
persistence true
persistence_location /mosquitto/data/

# Autosave interval (seconds)
autosave_interval 1800
EOF

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Nuova configurazione creata${NC}"
    echo ""
    echo "📄 Contenuto:"
    cat "$PROJECT_DIR/mosquitto/config/mosquitto.conf"
else
    echo -e "${RED}❌ Errore nella creazione della configurazione${NC}"
    exit 1
fi

echo ""

# ==================================================
# Riavvia Mosquitto
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Riavvio Mosquitto"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔄 Riavvio container Mosquitto..."
cd "$PROJECT_DIR"
docker-compose restart mosquitto

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Mosquitto riavviato con successo${NC}"
    echo ""
    echo "⏳ Attendo 3 secondi per stabilizzazione..."
    sleep 3
else
    echo -e "${RED}❌ Errore nel riavvio Mosquitto${NC}"
    exit 1
fi

echo ""

# ==================================================
# Verifica configurazione
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Verifica Configurazione"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Aggiorna container ID dopo riavvio
MOSQUITTO_ID=$(docker ps --filter "name=mosquitto" --format "{{.ID}}")

# Verifica porte
echo "🔍 Verifica porte in ascolto..."
echo ""

sleep 2

# Porta 1883
if netstat -tuln 2>/dev/null | grep -q ":1883" || ss -tuln 2>/dev/null | grep -q ":1883"; then
    echo -e "${GREEN}✅ Porta 1883 (MQTT): APERTA${NC}"
else
    echo -e "${RED}❌ Porta 1883: CHIUSA${NC}"
fi

# Porta 9001
if netstat -tuln 2>/dev/null | grep -q ":9001" || ss -tuln 2>/dev/null | grep -q ":9001"; then
    echo -e "${GREEN}✅ Porta 9001 (WebSocket): APERTA${NC}"
else
    echo -e "${RED}❌ Porta 9001: CHIUSA${NC}"
    echo -e "${YELLOW}⚠️  Attendi qualche secondo e riprova${NC}"
fi

echo ""

# Verifica logs Mosquitto
echo "📋 Ultimi log Mosquitto:"
docker logs --tail 10 mosquitto 2>&1 | tail -5
echo ""

# ==================================================
# Riepilogo
# ==================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 RIEPILOGO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${GREEN}✅ Configurazione Mosquitto aggiornata!${NC}"
echo ""
echo "🎯 Prossimi passi:"
echo ""
echo "1. Riavvia ESP32 (se già connesso)"
echo "2. Ricarica pagina frontend (Ctrl+F5)"
echo "3. Libera fotocellula ESP32"
echo "4. L'animazione dovrebbe partire!"
echo ""
echo "🔍 Per verificare:"
echo "   bash check_mosquitto_esterno.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0