// ParticleEditor.jsx
// Editor real-time per effetti particellari

import { useState, useEffect, useRef } from 'react'
import * as THREE from 'three'
import './ParticleEditor.css'

/**
 * ParticleEditor - UI per configurare effetti particellari in tempo reale
 * @param {Object} config - Configurazione particelle
 * @param {Function} onConfigChange - Callback quando configurazione cambia
 * @param {Function} onClose - Callback per chiudere editor
 * @param {Object} selectedObject - Oggetto sorgente particelle
 * @param {Function} onSelectSource - Callback per attivare selezione sorgente
 * @param {Function} onSelectTarget - Callback per attivare selezione target
 * @param {boolean} selectingMode - Se è attivo un picking mode
 */
export default function ParticleEditor({
  config = {},
  onConfigChange,
  onClose,
  selectedObject = null,
  onSelectSource,
  onSelectTarget,
  selectingMode = false
}) {
  // Stato configurazione locale
  const [localConfig, setLocalConfig] = useState({
    particleCount: config.particleCount || 500,
    particleSize: config.particleSize || 200,
    particleOpacity: config.particleOpacity || 1.0,
    speed: config.speed || 0.5,
    turbulence: config.turbulence || 0.3,
    maxDistance: config.maxDistance || 5.0,
    warmColor: config.warmColor || '#FF0000',
    hotColor: config.hotColor || '#FFFF00',
    distortionIntensity: config.distortionIntensity || 0.5,
    transmission: config.transmission || 1.0,
    thickness: config.thickness || 0.4,
    sourceObject: config.sourceObject || null,
    targetPosition: config.targetPosition || null
  })
  
  // Sincronizza config esterno con locale SOLO al mount
  useEffect(() => {
    setLocalConfig(prev => ({
      ...prev,
      ...config
    }))
  }, []) // ✅ Esegui SOLO al mount, ignora aggiornamenti esterni
  
  // Handler per cambio parametri + notifica parent
  const handleChange = (key, value) => {
    const newConfig = {
      ...localConfig,
      [key]: value
    }
    
    setLocalConfig(newConfig)
    
    // ✅ Notifica parent SOLO quando utente cambia parametri
    if (onConfigChange) {
      onConfigChange(newConfig)
    }
  }
  
  // Handler per export JSON
  const handleExportJSON = () => {
    const exportConfig = {
      ...localConfig,
      sourceObject: selectedObject?.name || null,
      timestamp: new Date().toISOString(),
      _notes: "Generated by ParticleEditor v1.0"
    }
    
    const json = JSON.stringify(exportConfig, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `particles_${selectedObject?.name || 'config'}_${Date.now()}.json`
    a.click()
    URL.revokeObjectURL(url)
    
    console.log('[ParticleEditor] 📋 Configurazione esportata:', exportConfig)
    alert('✅ Configurazione esportata con successo!')
  }
  
  // Handler per import JSON
  const handleImportJSON = () => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = '.json'
    
    input.onchange = async (e) => {
      try {
        const file = e.target.files[0]
        if (!file) return
        
        const text = await file.text()
        const imported = JSON.parse(text)
        
        console.log('[ParticleEditor] 📂 Configurazione importata:', imported)
        
        setLocalConfig(prev => ({
          ...prev,
          ...imported,
          sourceObject: prev.sourceObject, // Mantieni sorgente corrente
          targetPosition: imported.targetPosition || prev.targetPosition
        }))
        
        alert('✅ Configurazione caricata!')
        
      } catch (error) {
        console.error('[ParticleEditor] ❌ Errore import:', error)
        alert('❌ Errore nel caricamento del file JSON')
      }
    }
    
    input.click()
  }
  
  // Handler per reset configurazione
  const handleReset = () => {
    if (!confirm('⚠️ Ripristinare configurazione di default?')) return
    
    const defaultConfig = {
      particleCount: 500,
      particleSize: 200,
      particleOpacity: 1.0,
      speed: 0.5,
      turbulence: 0.3,
      maxDistance: 5.0,
      warmColor: '#FF0000',
      hotColor: '#FFFF00',
      distortionIntensity: 0.5,
      transmission: 1.0,
      thickness: 0.4,
      sourceObject: localConfig.sourceObject,
      targetPosition: localConfig.targetPosition
    }
    
    setLocalConfig(defaultConfig)
    alert('✅ Configurazione ripristinata!')
  }
  
  return (
    <div className="particle-editor">
      {/* Header */}
      <div className="particle-editor__header">
        <div className="particle-editor__title">
          🎨 Particle Editor
        </div>
        <button className="particle-editor__close" onClick={onClose}>
          ×
        </button>
      </div>
      
      {/* Oggetto sorgente */}
      <div className="particle-editor__section">
        <div className="particle-editor__section-title">Sorgente Particelle</div>
        
        {/* Toggle Preview Button */}
        <button
          className={`particle-editor__button ${config.enabled ? 'particle-editor__button--preview-on' : 'particle-editor__button--preview-off'}`}
          onClick={() => handleChange('enabled', !config.enabled)}
          style={{
            marginBottom: '12px',
            backgroundColor: config.enabled ? '#4CAF50' : '#666',
            fontWeight: 'bold'
          }}
        >
          {config.enabled ? '👁️ Preview ON' : '👁️‍🗨️ Preview OFF'}
        </button>
        
        {selectedObject ? (
          <div className="particle-editor__object-selected">
            <div className="particle-editor__object-name">
              {selectedObject.name || 'Unnamed Object'}
            </div>
            <div className="particle-editor__object-uuid">
              UUID: {selectedObject.uuid.substring(0, 8)}...
            </div>
          </div>
        ) : (
          <div className="particle-editor__no-selection">
            Nessun oggetto selezionato
          </div>
        )}
        
        <button
          className="particle-editor__button particle-editor__button--select"
          onClick={onSelectSource}
          disabled={selectingMode}
        >
          {selectingMode ? '⏳ Seleziona oggetto...' : '📍 Seleziona Sorgente'}
        </button>
      </div>
      
      <div className="particle-editor__divider" />
      
      {/* Target Position */}
      <div className="particle-editor__section">
        <div className="particle-editor__section-title">Direzione Target</div>
        
        {localConfig.targetPosition ? (
          <div className="particle-editor__target-info">
            <div style={{ fontSize: '11px', color: '#888', marginBottom: '4px' }}>
              Coordinate Target:
            </div>
            <div style={{ fontSize: '12px', color: '#00aaff', fontFamily: 'monospace' }}>
              X: {localConfig.targetPosition.x.toFixed(3)} | 
              Y: {localConfig.targetPosition.y.toFixed(3)} | 
              Z: {localConfig.targetPosition.z.toFixed(3)}
            </div>
          </div>
        ) : (
          <div className="particle-editor__no-target">
            Target non impostato
          </div>
        )}
        
        <button
          className="particle-editor__button particle-editor__button--select"
          onClick={onSelectTarget}
          disabled={selectingMode}
        >
          {selectingMode ? '⏳ Clicca punto target...' : '🎯 Imposta Target'}
        </button>
      </div>
      
      <div className="particle-editor__divider" />
      
      {/* Parametri Particelle */}
      <div className="particle-editor__section">
        <div className="particle-editor__section-title">Parametri Particelle</div>
        
        {/* Numero Particelle */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Numero Particelle</span>
            <span className="particle-editor__control-value">{localConfig.particleCount}</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="100"
            max="1000"
            step="50"
            value={localConfig.particleCount}
            onChange={(e) => handleChange('particleCount', parseInt(e.target.value))}
          />
        </div>
        
        {/* Dimensione */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Dimensione</span>
            <span className="particle-editor__control-value">{localConfig.particleSize}px</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="50"
            max="500"
            step="10"
            value={localConfig.particleSize}
            onChange={(e) => handleChange('particleSize', parseInt(e.target.value))}
          />
        </div>
        
        {/* Opacità */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Opacità</span>
            <span className="particle-editor__control-value">{(localConfig.particleOpacity * 100).toFixed(0)}%</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="0"
            max="1"
            step="0.05"
            value={localConfig.particleOpacity}
            onChange={(e) => handleChange('particleOpacity', parseFloat(e.target.value))}
          />
        </div>
        
        {/* Velocità */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Velocità</span>
            <span className="particle-editor__control-value">{localConfig.speed.toFixed(2)}</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="0.1"
            max="2.0"
            step="0.1"
            value={localConfig.speed}
            onChange={(e) => handleChange('speed', parseFloat(e.target.value))}
          />
        </div>
        
        {/* Turbolenza */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Turbolenza</span>
            <span className="particle-editor__control-value">{localConfig.turbulence.toFixed(2)}</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="0"
            max="1.0"
            step="0.05"
            value={localConfig.turbulence}
            onChange={(e) => handleChange('turbulence', parseFloat(e.target.value))}
          />
        </div>
        
        {/* Distanza Massima */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Distanza Max</span>
            <span className="particle-editor__control-value">{localConfig.maxDistance.toFixed(1)}m</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="1"
            max="10"
            step="0.5"
            value={localConfig.maxDistance}
            onChange={(e) => handleChange('maxDistance', parseFloat(e.target.value))}
          />
        </div>
        
        {/* Distorsione */}
        <div className="particle-editor__control">
          <div className="particle-editor__control-label">
            <span>Distorsione</span>
            <span className="particle-editor__control-value">{(localConfig.distortionIntensity * 100).toFixed(0)}%</span>
          </div>
          <input
            type="range"
            className="particle-editor__slider"
            min="0"
            max="1.0"
            step="0.05"
            value={localConfig.distortionIntensity}
            onChange={(e) => handleChange('distortionIntensity', parseFloat(e.target.value))}
          />
        </div>
      </div>
      
      <div className="particle-editor__divider" />
      
      {/* Colori */}
      <div className="particle-editor__section">
        <div className="particle-editor__section-title">Colori</div>
        
        <div className="particle-editor__color-controls">
          <div className="particle-editor__color-control">
            <label className="particle-editor__color-label">
              Colore Caldo (Base)
            </label>
            <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
              <input
                type="color"
                value={localConfig.warmColor}
                onChange={(e) => handleChange('warmColor', e.target.value)}
                className="particle-editor__color-picker"
              />
              <input
                type="text"
                value={localConfig.warmColor}
                onChange={(e) => handleChange('warmColor', e.target.value)}
                className="particle-editor__color-input"
                placeholder="#FF0000"
              />
            </div>
          </div>
          
          <div className="particle-editor__color-control">
            <label className="particle-editor__color-label">
              Colore Caldo (Peak)
            </label>
            <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
              <input
                type="color"
                value={localConfig.hotColor}
                onChange={(e) => handleChange('hotColor', e.target.value)}
                className="particle-editor__color-picker"
              />
              <input
                type="text"
                value={localConfig.hotColor}
                onChange={(e) => handleChange('hotColor', e.target.value)}
                className="particle-editor__color-input"
                placeholder="#FFFF00"
              />
            </div>
          </div>
        </div>
      </div>
      
      <div className="particle-editor__divider" />
      
      {/* Azioni */}
      <div className="particle-editor__section">
        <div className="particle-editor__actions">
          <button
            className="particle-editor__button particle-editor__button--export"
            onClick={handleExportJSON}
          >
            📋 Export JSON
          </button>
          
          <button
            className="particle-editor__button particle-editor__button--import"
            onClick={handleImportJSON}
          >
            📂 Import JSON
          </button>
          
          <button
            className="particle-editor__button particle-editor__button--reset"
            onClick={handleReset}
          >
            🔄 Reset
          </button>
        </div>
      </div>
      
      {/* Info Footer */}
      <div className="particle-editor__footer">
        <div style={{ fontSize: '11px', color: '#666', textAlign: 'center' }}>
          💡 Le modifiche si applicano in tempo reale<br/>
          Premi ESC per uscire dalla modalità selezione
        </div>
      </div>
    </div>
  )
}
