// useParticleEditor.js
// Hook per gestire lo stato e la logica del Particle Editor

import { useState, useCallback, useEffect } from 'react'
import * as THREE from 'three'

/**
 * Hook per gestire il Particle Editor
 * @returns {Object} Stato e funzioni per il particle editor
 */
export default function useParticleEditor() {
  // Stato editor
  const [editorOpen, setEditorOpen] = useState(false)
  const [selectingMode, setSelectingMode] = useState(null) // null | 'source' | 'target'
  const [selectedObject, setSelectedObject] = useState(null)
  const [targetPosition, setTargetPosition] = useState(null)
  
  // Configurazione particelle
  const [particleConfig, setParticleConfig] = useState({
    enabled: false,
    particleCount: 500,
    particleSize: 200,
    particleOpacity: 1.0,
    speed: 0.5,
    turbulence: 0.3,
    maxDistance: 5.0,
    warmColor: '#FF0000',
    hotColor: '#FFFF00',
    distortionIntensity: 0.5,
    transmission: 1.0,
    thickness: 0.4
  })
  
  // Apri/Chiudi editor
  const openEditor = useCallback(() => {
    console.log('[useParticleEditor] Editor aperto')
    setEditorOpen(true)
  }, [])
  
  const closeEditor = useCallback(() => {
    console.log('[useParticleEditor] Editor chiuso')
    setEditorOpen(false)
    setSelectingMode(null)
  }, [])
  
  // Toggle editor
  const toggleEditor = useCallback(() => {
    setEditorOpen(prev => !prev)
  }, [])
  
  // Attiva modalità selezione sorgente
  const startSelectingSource = useCallback(() => {
    console.log('[useParticleEditor] 📍 Modalità selezione sorgente attivata')
    setSelectingMode('source')
  }, [])
  
  // Attiva modalità selezione target
  const startSelectingTarget = useCallback(() => {
    console.log('[useParticleEditor] 🎯 Modalità selezione target attivata')
    setSelectingMode('target')
  }, [])
  
  // Annulla selezione
  const cancelSelecting = useCallback(() => {
    console.log('[useParticleEditor] ❌ Modalità selezione annullata')
    setSelectingMode(null)
  }, [])
  
  // Handler per selezione oggetto sorgente
  const handleObjectSelected = useCallback((object) => {
    if (selectingMode === 'source') {
      console.log('[useParticleEditor] ✅ Sorgente selezionata:', object.name)
      setSelectedObject(object)
      setSelectingMode(null)
      
      // Abilita particelle quando viene selezionata una sorgente
      setParticleConfig(prev => ({
        ...prev,
        enabled: true
      }))
    }
  }, [selectingMode])
  
  // Handler per selezione punto target
  const handleTargetSelected = useCallback((worldPosition) => {
    console.log('[useParticleEditor] 🎯 handleTargetSelected chiamato!')
    console.log('[useParticleEditor]   - selectingMode:', selectingMode)
    console.log('[useParticleEditor]   - worldPosition:', worldPosition)
    
    if (selectingMode === 'target') {
      console.log('[useParticleEditor] ✅ Target selezionato:', worldPosition)
      setTargetPosition(worldPosition)
      setSelectingMode(null)
    } else {
      console.warn('[useParticleEditor] ⚠️ selectingMode non è "target"! Valore attuale:', selectingMode)
    }
  }, [selectingMode])
  
  // Update configurazione
  const updateConfig = useCallback((newConfig) => {
    setParticleConfig(prev => ({
      ...prev,
      ...newConfig
    }))
  }, [])
  
  // Reset configurazione
  const resetConfig = useCallback(() => {
    console.log('[useParticleEditor] 🔄 Reset configurazione')
    setParticleConfig({
      enabled: selectedObject !== null,
      particleCount: 500,
      particleSize: 200,
      particleOpacity: 1.0,
      speed: 0.5,
      turbulence: 0.3,
      maxDistance: 5.0,
      warmColor: '#FF0000',
      hotColor: '#FFFF00',
      distortionIntensity: 0.5,
      transmission: 1.0,
      thickness: 0.4
    })
  }, [selectedObject])
  
  // Export configurazione
  const exportConfig = useCallback(() => {
    const config = {
      sourceObject: selectedObject?.name || null,
      sourceUUID: selectedObject?.uuid || null,
      targetPosition: targetPosition ? {
        x: targetPosition.x,
        y: targetPosition.y,
        z: targetPosition.z
      } : null,
      ...particleConfig,
      timestamp: new Date().toISOString(),
      _notes: "Generated by ParticleEditor v1.0"
    }
    
    console.log('[useParticleEditor] 📋 Export config:', config)
    return config
  }, [selectedObject, targetPosition, particleConfig])
  
  // Import configurazione
  const importConfig = useCallback((config) => {
    console.log('[useParticleEditor] 📂 Import config:', config)
    
    if (config.targetPosition) {
      setTargetPosition(new THREE.Vector3(
        config.targetPosition.x,
        config.targetPosition.y,
        config.targetPosition.z
      ))
    }
    
    setParticleConfig(prev => ({
      ...prev,
      ...config,
      enabled: selectedObject !== null
    }))
  }, [selectedObject])
  
  // Gestione ESC key per annullare selezione
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && selectingMode) {
        cancelSelecting()
      }
    }
    
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [selectingMode, cancelSelecting])
  
  // Gestione tasto "X" per toggle editor (P già usato per debug posizione)
  useEffect(() => {
    const handleKeyDown = (e) => {
      // Non attivare se sta digitando in un input
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return
      
      if (e.key === 'x' || e.key === 'X') {
        toggleEditor()
      }
    }
    
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [toggleEditor])
  
  return {
    // Stato
    editorOpen,
    selectingMode,
    selectedObject,
    targetPosition,
    particleConfig,
    
    // Azioni editor
    openEditor,
    closeEditor,
    toggleEditor,
    
    // Azioni selezione
    startSelectingSource,
    startSelectingTarget,
    cancelSelecting,
    handleObjectSelected,
    handleTargetSelected,
    
    // Azioni configurazione
    updateConfig,
    resetConfig,
    exportConfig,
    importConfig,
    
    // Setter diretti (per casi speciali)
    setSelectedObject,
    setTargetPosition,
    setParticleConfig
  }
}
